### PR TITLE
Avoid NRE when removing nodes with SyntaxRemoveOptions other than KeepNoTrivia

### PR DESCRIPTION
**Pull request by yankarinRG**

### CODE REVIEW

**Review by KirillOsenkov — APPROVED** [review]
:+1:

**Comment by KirillOsenkov** [comment]
Thanks!

**Comment by KirillOsenkov** [comment]
Published https://www.nuget.org/packages/GuiLabs.Language.Xml/1.2.93

**Comment by yankarinRG** [comment]
Thank you for the quick merge! 😊

**Pull request merged**
